name: Verify package
on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - synchronize
      - reopened
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Verify package
        run: ./mvnw verify
